# Generated by Django 5.2.5 on 2025-08-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioupload',
            name='spectrogram',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
    ]
