# Generated by Django 5.2.5 on 2025-09-02 11:58

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audioupload_spectrogram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Audio subido', 'verbose_name_plural': 'Audios subidos'},
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='file',
            field=models.FileField(help_text='Sube un archivo de audio para analizar', upload_to=audio.models.ruta_archivo_audio, verbose_name='Archivo de audio'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='probability',
            field=models.FloatField(blank=True, help_text='Nivel de confianza del resultado', null=True, verbose_name='Probabilidad'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='result',
            field=models.CharField(blank=True, help_text="Indica si el audio es 'real' o 'fake'", max_length=20, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='spectrogram',
            field=models.ImageField(blank=True, help_text='Imagen del espectrograma generado', null=True, upload_to=audio.models.ruta_espectrograma, verbose_name='Espectrograma'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
    ]
