# Generated by Django 5.2.5 on 2025-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_alter_audioupload_options_alter_audioupload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioupload',
            name='original_filename',
            field=models.CharField(default='', help_text='Nombre original del archivo subido', max_length=255, verbose_name='Nombre original del archivo'),
            preserve_default=False,
        ),
    ]
