# Generated by Django 5.2.5 on 2025-09-07 23:22

import audio.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_audioupload_original_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioupload',
            options={},
        ),
        migrations.RemoveField(
            model_name='audioupload',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='audioupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Nombre original del archivo subido', max_length=255, null=True, verbose_name='Nombre original del archivo'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='probability',
            field=models.FloatField(blank=True, null=True, verbose_name='Probabilidad del resultado'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado del análisis'),
        ),
        migrations.AlterField(
            model_name='audioupload',
            name='spectrogram',
            field=models.ImageField(blank=True, null=True, upload_to=audio.models.ruta_espectrograma, verbose_name='Espectrograma'),
        ),
    ]
