# Generated by Django 5.2.7 on 2025-10-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/codigo/')),
                ('filename', models.CharField(max_length=255)),
                ('lenguaje', models.CharField(blank=True, max_length=50)),
                ('ast_json', models.JSONField(blank=True, null=True)),
                ('complejidad', models.FloatField(blank=True, null=True)),
                ('predict_score', models.FloatField(blank=True, null=True)),
                ('report_path', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
