# Generated by Django 5.2.7 on 2025-10-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoupload',
            name='lenguaje',
        ),
        migrations.RemoveField(
            model_name='codigoupload',
            name='report_path',
        ),
        migrations.AddField(
            model_name='codigoupload',
            name='naming_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codigoupload',
            name='repetitividad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codigoupload',
            name='tipo_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='codigoupload',
            name='ast_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codigoupload',
            name='complejidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='codigoupload',
            name='file',
            field=models.FileField(upload_to='codigo/'),
        ),
        migrations.AlterField(
            model_name='codigoupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='codigoupload',
            name='predict_score',
            field=models.FloatField(default=0),
        ),
    ]
