# Generated by Django 5.2.7 on 2025-11-15 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0002_remove_codigoupload_lenguaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='codigo/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('lenguaje', models.CharField(blank=True, max_length=50, null=True)),
                ('ia_es_generado', models.BooleanField(default=False)),
                ('ia_confianza', models.FloatField(default=0.0)),
                ('ia_metodo', models.CharField(blank=True, max_length=100, null=True)),
                ('ia_detalles', models.JSONField(blank=True, null=True)),
                ('ast_json', models.JSONField(blank=True, null=True)),
                ('complejidad_ciclomatica', models.FloatField(default=0)),
                ('variabilidad_funciones', models.FloatField(default=0)),
                ('patrones_control', models.JSONField(blank=True, null=True)),
                ('patrones_comunes', models.JSONField(blank=True, null=True)),
                ('idiosincrasias', models.JSONField(blank=True, null=True)),
                ('indice_predictibilidad', models.FloatField(default=0)),
                ('lineas_sospechosas', models.JSONField(blank=True, null=True)),
                ('bloques_sospechosos', models.JSONField(blank=True, null=True)),
                ('reporte_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('reporte_json', models.JSONField(blank=True, null=True)),
                ('version_modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp_modelo', models.DateTimeField(blank=True, null=True)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.DeleteModel(
            name='CodigoUpload',
        ),
    ]
