# Generated by Django 5.2.5 on 2025-09-02 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto analizado')),
                ('resultado_prediccion', models.CharField(choices=[('IA', 'Inteligencia Artificial'), ('HUMANO', 'Humano')], max_length=10, verbose_name='Resultado de predicción')),
                ('probabilidad_ia', models.FloatField(verbose_name='Probabilidad IA (%)')),
                ('probabilidad_humano', models.FloatField(verbose_name='Probabilidad Humano (%)')),
                ('fecha_analisis', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de análisis')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario', verbose_name='Usuario que realizó el análisis')),
            ],
            options={
                'verbose_name': 'Análisis de texto',
                'verbose_name_plural': 'Análisis de textos',
                'ordering': ['-fecha_analisis'],
            },
        ),
    ]
