# Generated by Django 5.2.5 on 2025-09-06 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField()),
                ('prediccion', models.CharField(choices=[('IA', 'Generado por IA'), ('HUMANO', 'Escrito por Humano')], max_length=10)),
                ('probabilidad_ia', models.FloatField()),
                ('probabilidad_humano', models.FloatField()),
                ('confianza', models.CharField(max_length=10)),
                ('modelo_utilizado', models.CharField(max_length=50)),
                ('tipo_entrada', models.CharField(choices=[('TEXTO', 'Texto directo'), ('ARCHIVO', 'Archivo subido')], default='TEXTO', max_length=10)),
                ('fecha_analisis', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Texto',
                'verbose_name_plural': 'Análisis de Textos',
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_archivo_original', models.CharField(blank=True, max_length=500, null=True)),
                ('hash_archivo', models.CharField(blank=True, max_length=64, null=True)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archivo_info', to='texto.analisistexto')),
            ],
            options={
                'verbose_name': 'Archivo de Análisis',
                'verbose_name_plural': 'Archivos de Análisis',
                'db_table': 'archivo_analisis',
            },
        ),
    ]
