# Generated by Django 5.2.5 on 2025-09-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texto', '0002_add_file_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisistexto',
            options={'ordering': ['-fecha_analisis'], 'verbose_name': 'Análisis de Texto', 'verbose_name_plural': 'Análisis de Textos'},
        ),
        migrations.AlterField(
            model_name='analisistexto',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='analisistexto',
            name='resultado_prediccion',
            field=models.CharField(choices=[('IA', 'Generado por IA'), ('HUMANO', 'Escrito por Humano')], max_length=10, verbose_name='Resultado de predicción'),
        ),
        migrations.AlterField(
            model_name='analisistexto',
            name='tamano_archivo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (en bytes)'),
        ),
        migrations.AlterField(
            model_name='analisistexto',
            name='tipo_archivo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de archivo'),
        ),
        migrations.AlterField(
            model_name='analisistexto',
            name='tipo_entrada',
            field=models.CharField(choices=[('TEXTO', 'Texto directo'), ('ARCHIVO', 'Archivo subido')], default='TEXTO', max_length=10, verbose_name='Tipo de entrada'),
        ),
        migrations.AlterModelTable(
            name='analisistexto',
            table='analisis_texto',
        ),
    ]
